# Generated by Django 5.0.3 on 2026-06-14 20:16

import datetime
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_current_documents(apps, schema_editor):
    Document = apps.get_model("career", "Document")

    groups = {}
    for doc in Document.objects.all():
        root_id = doc.root_document_id or doc.id
        groups.setdefault(root_id, []).append(doc)

    for _root_id, docs in groups.items():
        docs_sorted = sorted(
            docs,
            key=lambda d: (d.version_number or 1, d.updated_at, d.id),
            reverse=True,
        )
        current_doc = docs_sorted[0]
        Document.objects.filter(id=current_doc.id).update(is_current=True)
        stale_ids = [d.id for d in docs_sorted[1:]]
        if stale_ids:
            Document.objects.filter(id__in=stale_ids).update(is_current=False)


def blank_unknown_decision_signals(apps, schema_editor):
    Application = apps.get_model("career", "Application")
    Application.objects.filter(visa_sponsorship="UNKNOWN").update(visa_sponsorship="")
    Application.objects.filter(day_one_gc="UNKNOWN").update(day_one_gc="")


def restore_unknown_decision_signals(apps, schema_editor):
    Application = apps.get_model("career", "Application")
    Application.objects.filter(visa_sponsorship="").update(visa_sponsorship="UNKNOWN")
    Application.objects.filter(day_one_gc="").update(day_one_gc="UNKNOWN")


def set_reminder_note_default(apps, schema_editor):
    table_name = "career_applicationtimelineentry"
    column_name = "reminder_note"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
    if column_name not in existing_columns:
        return

    quote_name = connection.ops.quote_name
    quoted_table = quote_name(table_name)
    quoted_column = quote_name(column_name)

    with connection.cursor() as cursor:
        cursor.execute(
            f"UPDATE {quoted_table} SET {quoted_column} = %s WHERE {quoted_column} IS NULL",
            [""],
        )
        if connection.vendor == "postgresql":
            cursor.execute(
                f"ALTER TABLE {quoted_table} ALTER COLUMN {quoted_column} SET DEFAULT ''"
            )


def unset_reminder_note_default(apps, schema_editor):
    table_name = "career_applicationtimelineentry"
    column_name = "reminder_note"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
    if column_name not in existing_columns or connection.vendor != "postgresql":
        return

    quote_name = connection.ops.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            f"ALTER TABLE {quote_name(table_name)} ALTER COLUMN {quote_name(column_name)} DROP DEFAULT"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('job_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('OA', 'Online Assessment'), ('SCREEN', 'Phone Screen'), ('ONSITE', 'Onsite Interview'), ('OFFER', 'Offer Received'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('GHOSTED', 'Ghosted')], default='APPLIED', max_length=20)),
                ('rto_policy', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. $150k - $180k', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='career.company')),
                ('current_round', models.IntegerField(default=0, help_text='Current interview round number (0 for none)')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked applications cannot be deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Annual Base Salary', max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, help_text='Annual Target Bonus', max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, default=0, help_text='Annualized Equity Value', max_digits=12)),
                ('sign_on', models.DecimalField(decimal_places=2, default=0, help_text='One-time Sign On Bonus', max_digits=12)),
                ('benefits_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated Annual Benefits Value', max_digits=12)),
                ('pto_days', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='career.application')),
                ('is_current', models.BooleanField(default=False, help_text='Is this your current role?')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'position', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('COVER_LETTER', 'Cover Letter'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], default='RESUME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='career.application')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked documents cannot be deleted')),
                ('is_current', models.BooleanField(default=True)),
                ('root_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='career.document')),
                ('version_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RunPython(
            code=backfill_current_documents,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='application',
            name='rto_days_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='commute_cost_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='commute_cost_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='free_food_perk_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='free_food_perk_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_rent_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tax_base_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tax_bonus_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tax_equity_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='holiday_days',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='offer',
            name='benefit_items',
            field=models.JSONField(blank=True, default=list, help_text='Benefit item breakdown used to derive annual benefits value'),
        ),
        migrations.AddField(
            model_name='offer',
            name='equity_total_grant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total equity grant value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='equity_vesting_percent',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Annual vesting percent used for annualized equity', max_digits=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='raise_history',
            field=models.JSONField(blank=True, default=list, help_text='List of raise events [{id, date, type, base_before, base_after, bonus_before, bonus_after, equity_before, equity_after, label, notes}]'),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_unlimited_pto',
            field=models.BooleanField(default=False, help_text='Offer includes unlimited PTO'),
        ),
        migrations.AddField(
            model_name='application',
            name='office_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='experience_logos/')),
                ('is_promotion', models.BooleanField(default=False, help_text='Groups this role with the previous role at the same company as a promotion')),
                ('is_locked', models.BooleanField(blank=True, default=False, help_text='Locked roles cannot be edited or deleted', null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20, null=True)),
                ('offer', models.ForeignKey(blank=True, help_text='Linked offer for raise history tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='career.offer')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly pay rate (for internships)', max_digits=8, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual base salary', max_digits=12, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, help_text='Annual target bonus', max_digits=12, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, help_text='Annualized equity value', max_digits=12, null=True)),
                ('team_history', models.JSONField(blank=True, default=list, help_text='List of team entries [{id, name, start_date, end_date, is_current, norms}]')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned experiences appear at the top of the list')),
                ('hours_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Typical hours worked per day for hourly roles', max_digits=5, null=True)),
                ('total_hours_worked', models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual override for total hours worked in an hourly role', max_digits=8, null=True)),
                ('working_days_per_week', models.DecimalField(blank=True, decimal_places=2, help_text='Typical working days per week for hourly roles', max_digits=4, null=True)),
                ('total_earnings_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual override for total internship earnings', max_digits=12, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Optional overtime hours worked in an hourly role', max_digits=8, null=True)),
                ('overtime_multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='Optional overtime multiplier when overtime rate is derived from hourly rate', max_digits=5, null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional explicit overtime hourly rate', max_digits=8, null=True)),
                ('schedule_phases', models.JSONField(blank=True, default=list, help_text='List of schedule phases [{id, name, start_date, end_date, is_current, hourly_rate, hours_per_day, working_days_per_week, total_hours_worked, overtime_hours, overtime_rate, overtime_multiplier, total_earnings_override}]')),
                ('is_return_offer', models.BooleanField(default=False, help_text='Marks this role as having originated from a return internship offer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_company_per_user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, default='full_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, default='full_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='brand_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manual company brand score from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='application',
            name='day_one_gc',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('YES', 'Yes'), ('NO', 'No'), ('NOT_APPLICABLE', 'Not applicable')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='growth_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manual growth score from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='application',
            name='team_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manual manager/team score from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_sponsorship',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NOT_NEEDED', 'Not needed'), ('AVAILABLE', 'Sponsorship available'), ('TRANSFER_ONLY', 'Transfer only'), ('NOT_AVAILABLE', 'No sponsorship')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='work_life_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manual work-life balance score from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied'), ('OA', 'Online Assessment'), ('SCREEN', 'Phone Screen'), ('ONSITE', 'Onsite Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('GHOSTED', 'Ghosted')], max_length=20)),
                ('stage_order', models.PositiveSmallIntegerField(default=999)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='career.application')),
                ('documents', models.ManyToManyField(blank=True, related_name='timeline_entries', to='career.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application_id', 'stage_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationtimelineentry',
            constraint=models.UniqueConstraint(fields=('user', 'application', 'stage'), name='unique_timeline_stage_per_application'),
        ),
        migrations.RunPython(
            code=blank_unknown_decision_signals,
            reverse_code=restore_unknown_decision_signals,
        ),
        migrations.AlterField(
            model_name='application',
            name='day_one_gc',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('YES', 'Yes'), ('NO', 'No'), ('NOT_APPLICABLE', 'Not applicable')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='visa_sponsorship',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('NOT_NEEDED', 'Not needed'), ('AVAILABLE', 'Sponsorship available'), ('TRANSFER_ONLY', 'Transfer only'), ('NOT_AVAILABLE', 'No sponsorship')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='APPLIED', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationtimelineentry',
            name='stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='equity_vesting_schedule',
            field=models.JSONField(blank=True, default=list, help_text='Four-year equity vesting percentages, e.g. [20, 20, 30, 30]'),
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sheet_url', models.URLField(max_length=2048)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255)),
                ('worksheet_name', models.CharField(blank=True, max_length=255)),
                ('gid', models.CharField(blank=True, max_length=64)),
                ('target_type', models.CharField(choices=[('APPLICATIONS', 'Applications'), ('EVENTS', 'Events')], max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('header_row', models.PositiveSmallIntegerField(default=1)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('IDLE', 'Idle'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='IDLE', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheet_sync_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(max_length=64)),
                ('local_object_type', models.CharField(max_length=50)),
                ('local_object_id', models.PositiveIntegerField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_rows', to='career.googlesheetsyncconfig')),
            ],
        ),
        migrations.AddConstraint(
            model_name='googlesheetsyncconfig',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_google_sheet_sync_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='googlesheetsyncrow',
            constraint=models.UniqueConstraint(fields=('config', 'external_key'), name='unique_google_sheet_row_per_config'),
        ),
        migrations.AddField(
            model_name='googlesheetsyncconfig',
            name='sync_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Preferred daily sync time in sync_timezone.'),
        ),
        migrations.AddField(
            model_name='googlesheetsyncconfig',
            name='sync_timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=64),
        ),
        migrations.CreateModel(
            name='GoogleOAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128, unique=True)),
                ('redirect_url', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('JD_REPORT', 'JD Report'), ('COVER_LETTER', 'Cover Letter'), ('NEGOTIATION_RESULT', 'Negotiation Result')], max_length=40)),
                ('client_id', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_artifacts', to='career.application')),
                ('source_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_artifacts', to='career.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiartifact',
            constraint=models.UniqueConstraint(fields=('user', 'client_id'), name='unique_ai_artifact_client_id_per_user'),
        ),
        migrations.CreateModel(
            name='OfferDecisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('decision_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_comp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commute_cost_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_snapshot', models.JSONField(blank=True, default=dict)),
                ('score_categories', models.JSONField(blank=True, default=list)),
                ('offer_snapshot', models.JSONField(blank=True, default=dict)),
                ('adjustment_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_snapshots', to='career.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_decision_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='googlesheetsyncconfig',
            name='overwrite_strategies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('ROLLED_BACK', 'Rolled Back')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('error_details', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='career.googlesheetsyncconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='source_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='source_removed_delete_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='source_removed_previous_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='googlesheetsyncconfig',
            name='missing_row_strategy',
            field=models.CharField(choices=[('IGNORE', 'Ignore missing rows'), ('ARCHIVE_THEN_DELETE', 'Archive then delete missing rows')], default='ARCHIVE_THEN_DELETE', max_length=30),
        ),
        migrations.AddField(
            model_name='googlesheetsyncconfig',
            name='missing_row_delete_after_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.RunPython(
            code=set_reminder_note_default,
            reverse_code=unset_reminder_note_default,
        ),
        migrations.AddField(
            model_name='aiartifact',
            name='source_experience',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_artifacts', to='career.experience'),
        ),
        migrations.AlterField(
            model_name='aiartifact',
            name='artifact_type',
            field=models.CharField(choices=[('JD_REPORT', 'JD Report'), ('COVER_LETTER', 'Cover Letter'), ('NEGOTIATION_RESULT', 'Negotiation Result'), ('PROMOTION_REVIEW', 'Promotion Review')], max_length=40),
        ),
        migrations.CreateModel(
            name='AIArtifactGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROMOTION_REVIEW', 'Promotion Review')], max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='career.aiartifact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artifact_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
