# Generated by Django 5.0.3 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "career_application" ADD COLUMN "flexible_hours_policy" varchar(20) DEFAULT \'UNKNOWN\' NOT NULL;',
                    reverse_sql='ALTER TABLE "career_application" DROP COLUMN "flexible_hours_policy";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_application" ADD COLUMN "travel_frequency" varchar(20) DEFAULT \'UNKNOWN\' NOT NULL;',
                    reverse_sql='ALTER TABLE "career_application" DROP COLUMN "travel_frequency";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "forty_one_k_match_percent" numeric(5, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "forty_one_k_match_percent";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "forty_one_k_max_match" numeric(5, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "forty_one_k_max_match";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "health_oop_max" numeric(10, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "health_oop_max";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "health_plan_type" varchar(50) DEFAULT \'\' NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "health_plan_type";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "health_premium_monthly" numeric(10, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "health_premium_monthly";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "hsa_employer_contribution" numeric(10, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "hsa_employer_contribution";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "career_offer" ADD COLUMN "relocation_bonus" numeric(12, 2) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE "career_offer" DROP COLUMN "relocation_bonus";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="flexible_hours_policy",
                    field=models.CharField(
                        choices=[
                            ("FLEXIBLE", "Flexible Hours"),
                            ("CORE_HOURS", "Core Hours"),
                            ("STRICT", "Strict Hours"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="application",
                    name="travel_frequency",
                    field=models.CharField(
                        choices=[
                            ("NONE", "No Travel"),
                            ("LOW", "Low Travel (<10%)"),
                            ("MEDIUM", "Medium Travel (10-25%)"),
                            ("HIGH", "High Travel (>25%)"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="forty_one_k_match_percent",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employer 401(k) Match Percentage (e.g. 50.00 for 50%)",
                        max_digits=5,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="forty_one_k_max_match",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum Employee 401(k) Contribution matched (e.g. 6.00 for 6%)",
                        max_digits=5,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_oop_max",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual Health Out-of-Pocket Maximum",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_plan_type",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="Health Plan Type, e.g. HDHP, PPO",
                        max_length=50,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_premium_monthly",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly Health Insurance Premium",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="hsa_employer_contribution",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual Employer HSA Contribution",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="relocation_bonus",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-time Relocation or Signing Perk Cash Value",
                        max_digits=12,
                    ),
                ),
            ]
        )
    ]
