# Generated by Django 5.0.3 on 2026-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0002_application_current_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("OA", "Online Assessment"),
                    ("SCREEN", "Phone Screen"),
                    ("ONSITE", "Onsite Interview"),
                    ("OFFER", "Offer Received"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                    ("GHOSTED", "Ghosted"),
                ],
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
