# Generated by Django 5.0.3 on 2026-09-07 23:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0002_offer_unlimited_pto_planning_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferDecisionJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("DECLINED", "Declined")],
                        max_length=10,
                    ),
                ),
                ("decided_on", models.DateField(help_text="When the call was made")),
                ("started_on", models.DateField(blank=True, null=True)),
                (
                    "reasons",
                    models.TextField(
                        blank=True,
                        help_text="What made this the right call at the time",
                    ),
                ),
                (
                    "concerns",
                    models.TextField(
                        blank=True, help_text="What you were worried about"
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="How sure you were, 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "reviews",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="One entry per milestone: [{milestone, completed_on, verdict, notes, confidence}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_journal",
                        to="career.offer",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_on"],
            },
        ),
    ]
