# Generated by Django 5.0.3 on 2026-09-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0003_offer_decision_journal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerdecisionjournal",
            name="confidence",
        ),
        migrations.AlterField(
            model_name="offerdecisionjournal",
            name="reviews",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="One entry per milestone: [{milestone, completed_on, verdict, notes}]",
            ),
        ),
    ]
