# Generated by Django 5.0.3 on 2026-09-21 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TABLE = "career_offer"
COLUMNS = ["pto_rollover_max_days", "pto_rollover_expires_month"]


def add_columns(apps, schema_editor):
    for column in COLUMNS:
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(
                f"ALTER TABLE {TABLE} ADD COLUMN IF NOT EXISTS {column} smallint NOT NULL DEFAULT 0"
            )
        else:
            # sqlite rejects IF NOT EXISTS on ADD COLUMN, and a fresh build never has the column.
            schema_editor.execute(
                f"ALTER TABLE {TABLE} ADD COLUMN {column} smallint NOT NULL DEFAULT 0"
            )


def drop_columns(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for column in COLUMNS:
        schema_editor.execute(f"ALTER TABLE {TABLE} DROP COLUMN IF EXISTS {column}")



class Migration(migrations.Migration):
    dependencies = [
        ("career", "0004_drop_premium_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Raw ADD COLUMN: the generated AddField emits an ALTER COLUMN DROP DEFAULT that Nile rejects.
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_columns, drop_columns)],
            state_operations=[
                migrations.AddField(
                    model_name="offer",
                    name="pto_rollover_expires_month",
                    field=models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Month the carried days lapse, 1-12. 0 means they never lapse.",
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="pto_rollover_max_days",
                    field=models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Unused days that carry into next year. 0 means none carry.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeOffEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=1,
                        default=1,
                        help_text="A half day is the smallest unit payroll tracks, so 0.5 rather than hours",
                        max_digits=3,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PTO", "Paid time off"),
                            ("SICK", "Sick leave"),
                            ("UNPAID", "Unpaid leave"),
                        ],
                        default="PTO",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience",
                    models.ForeignKey(
                        help_text="Which role the day was taken against; a job change starts a fresh balance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off_entries",
                        to="career.experience",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("experience", "date", "kind")},
            },
        ),
    ]
