# Generated by Django 5.0.3 on 2026-09-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0004_offer_decision_journal_drop_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerdecisionjournal",
            name="criteria",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Scorecard category keys that drove the call, e.g. ['financial', 'trajectory']",
            ),
        ),
        migrations.AlterField(
            model_name="offerdecisionjournal",
            name="concerns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{id, text, outcome}] where outcome is REAL, AVOIDED, UNCLEAR or null",
            ),
        ),
        migrations.AlterField(
            model_name="offerdecisionjournal",
            name="reviews",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{milestone, completed_on, verdict, notes, criteria_verdicts}]",
            ),
        ),
    ]
