# Generated by Django 5.0.3 on 2026-09-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0005_offer_decision_journal_outcomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="expected_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
