# Generated by Django 5.0.3 on 2026-02-22 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0006_application_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESUME", "Resume"),
                            ("COVER_LETTER", "Cover Letter"),
                            ("PORTFOLIO", "Portfolio"),
                            ("OTHER", "Other"),
                        ],
                        default="RESUME",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="career.application",
                    ),
                ),
            ],
        ),
    ]
