# Generated by Django 5.0.3 on 2026-09-12 19:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0006_offer_expected_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Ticker, stored uppercase", max_length=12
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "as_of",
                    models.DateField(help_text="The trading day this price belongs to"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Entered by hand"),
                            ("API", "Fetched from a market data provider"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_price_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of", "symbol"],
            },
        ),
        migrations.AddConstraint(
            model_name="stockpricehistory",
            constraint=models.UniqueConstraint(
                fields=("user", "symbol", "as_of"),
                name="unique_stock_price_history_per_day",
            ),
        ),
    ]
