# Generated by Django 5.0.3 on 2026-07-27 03:25

from django.db import migrations, models


OFFER_DETAIL_COLUMNS = {
    'dental_annual_max': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dental_deductible': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dental_monthly_premium': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dental_plan_name': "varchar(100) DEFAULT '' NOT NULL",
    'dental_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dependent_count': 'integer DEFAULT 0 NOT NULL',
    'dependent_coverage_tier': "varchar(50) DEFAULT 'EMPLOYEE_SPOUSE' NOT NULL",
    'dependent_dental_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dependent_health_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'dependent_vision_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'has_dependents': 'boolean DEFAULT false NOT NULL',
    'health_deductible': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'health_family_deductible': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'health_family_oop_max': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'health_pcp_copay': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'health_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'health_specialist_copay': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'paychecks_per_year': 'integer DEFAULT 26 NOT NULL',
    'vision_contacts_allowance': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'vision_frames_allowance': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'vision_monthly_premium': 'numeric(10, 2) DEFAULT 0 NOT NULL',
    'vision_plan_name': "varchar(100) DEFAULT '' NOT NULL",
    'vision_premium_paycheck': 'numeric(10, 2) DEFAULT 0 NOT NULL',
}


def add_offer_detail_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor not in {'postgresql', 'sqlite'}:
        return
    table_name = 'career_offer'
    with connection.cursor() as cursor:
        existing = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
    quote_name = connection.ops.quote_name
    with connection.cursor() as cursor:
        for column_name, definition in OFFER_DETAIL_COLUMNS.items():
            if column_name in existing:
                continue
            cursor.execute(
                f'ALTER TABLE {quote_name(table_name)} '
                f'ADD COLUMN {quote_name(column_name)} {definition}'
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("career", "0013_experience_position"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_offer_detail_columns, migrations.RunPython.noop)
            ],
            state_operations=[
                migrations.AddField(
                    model_name="offer",
                    name="dental_annual_max",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_monthly_premium",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_plan_name",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Dental premium per paycheck",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_count",
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_coverage_tier",
                    field=models.CharField(
                        blank=True, default="EMPLOYEE_SPOUSE", max_length=50
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_dental_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_health_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_vision_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="has_dependents",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_family_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_family_oop_max",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_pcp_copay",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Medical premium per paycheck",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_specialist_copay",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="paychecks_per_year",
                    field=models.IntegerField(
                        default=26, help_text="Number of paychecks per year (e.g. 26 or 27)"
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_contacts_allowance",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_frames_allowance",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_monthly_premium",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_plan_name",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Vision premium per paycheck",
                        max_digits=10,
                    ),
                ),
            ],
        ),
    ]
