# Generated by Django 5.0.3 on 2026-07-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("career", "0013_experience_position"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dental_annual_max" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dental_deductible" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dental_monthly_premium" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dental_plan_name" varchar(100) DEFAULT '' NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dental_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dependent_count" integer DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dependent_coverage_tier" varchar(50) DEFAULT 'EMPLOYEE_SPOUSE' NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dependent_dental_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dependent_health_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "dependent_vision_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "has_dependents" boolean DEFAULT false NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_deductible" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_family_deductible" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_family_oop_max" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_pcp_copay" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "health_specialist_copay" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "paychecks_per_year" integer DEFAULT 26 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "vision_contacts_allowance" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "vision_frames_allowance" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "vision_monthly_premium" numeric(10, 2) DEFAULT 0 NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "vision_plan_name" varchar(100) DEFAULT '' NOT NULL;
                    ALTER TABLE "career_offer" ADD COLUMN IF NOT EXISTS "vision_premium_paycheck" numeric(10, 2) DEFAULT 0 NOT NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dental_annual_max";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dental_deductible";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dental_monthly_premium";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dental_plan_name";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dental_premium_paycheck";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dependent_count";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dependent_coverage_tier";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dependent_dental_premium_paycheck";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dependent_health_premium_paycheck";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "dependent_vision_premium_paycheck";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "has_dependents";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_deductible";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_family_deductible";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_family_oop_max";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_pcp_copay";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_premium_paycheck";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "health_specialist_copay";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "paychecks_per_year";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "vision_contacts_allowance";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "vision_frames_allowance";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "vision_monthly_premium";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "vision_plan_name";
                    ALTER TABLE "career_offer" DROP COLUMN IF EXISTS "vision_premium_paycheck";
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="offer",
                    name="dental_annual_max",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_monthly_premium",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_plan_name",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dental_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Dental premium per paycheck",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_count",
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_coverage_tier",
                    field=models.CharField(
                        blank=True, default="EMPLOYEE_SPOUSE", max_length=50
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_dental_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_health_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="dependent_vision_premium_paycheck",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="has_dependents",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_family_deductible",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_family_oop_max",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_pcp_copay",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Medical premium per paycheck",
                        max_digits=10,
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="health_specialist_copay",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="paychecks_per_year",
                    field=models.IntegerField(
                        default=26, help_text="Number of paychecks per year (e.g. 26 or 27)"
                    ),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_contacts_allowance",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_frames_allowance",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_monthly_premium",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_plan_name",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="offer",
                    name="vision_premium_paycheck",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Vision premium per paycheck",
                        max_digits=10,
                    ),
                ),
            ],
        ),
    ]
