# Generated by Django 5.0.3 on 2026-07-27 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0014_offer_dental_annual_max_offer_dental_deductible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerdecisionsnapshot",
            name="decision_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
