# Generated by Django 5.0.3 on 2026-08-01 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0015_alter_offerdecisionsnapshot_decision_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="counteroffer_history",
        ),
    ]
