# Generated by Django 5.0.3 on 2026-08-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # This engine rejects three things Django emits by default: ALTER COLUMN ...
    # DROP DEFAULT, an inline CONSTRAINT on ADD COLUMN, and SET CONSTRAINTS (issued
    # when a deferrable FK is recreated). Each is worked around with raw SQL below,
    # so the migration can stay atomic.

    dependencies = [
        ("career", "0019_applicationcontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Split in two: this engine rejects an inline ``CONSTRAINT ... REFERENCES`` on
        # ADD COLUMN, but accepts a separate ADD CONSTRAINT. See migration 0017 for
        # the related DROP DEFAULT limitation.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "career_applicationcontact" '
                        'ADD COLUMN "experience_id" bigint NULL;'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "career_applicationcontact" DROP COLUMN "experience_id";'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "career_applicationcontact" '
                        'ADD CONSTRAINT "career_contact_experience_fk" '
                        'FOREIGN KEY ("experience_id") REFERENCES "career_experience" ("id");'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "career_applicationcontact" '
                        'DROP CONSTRAINT "career_contact_experience_fk";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="applicationcontact",
                    name="experience",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="career.experience",
                    ),
                ),
            ],
        ),
        # Wrapped because this engine rejects the ``ALTER COLUMN ... DROP DEFAULT``
        # Django emits after adding a defaulted column. See migration 0017.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "career_experience" '
                        "ADD COLUMN \"work_email\" varchar(254) DEFAULT '' NOT NULL;"
                    ),
                    reverse_sql='ALTER TABLE "career_experience" DROP COLUMN "work_email";',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="experience",
                    name="work_email",
                    field=models.EmailField(
                        blank=True,
                        help_text="Your work email address at this job",
                        max_length=254,
                    ),
                ),
            ],
        ),
        # Only nullability changes here. Django would drop and recreate the FK as
        # deferrable and then issue SET CONSTRAINTS, which this engine rejects; the
        # existing constraint stays valid either way.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "career_applicationcontact" '
                        'ALTER COLUMN "application_id" DROP NOT NULL;'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "career_applicationcontact" '
                        'ALTER COLUMN "application_id" SET NOT NULL;'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="applicationcontact",
                    name="application",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="career.application",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="applicationcontact",
            index=models.Index(
                fields=["user", "experience"], name="career_contact_exp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcontact",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("application__isnull", False),
                    ("experience__isnull", False),
                    _connector="OR",
                ),
                name="contact_has_application_or_experience",
            ),
        ),
    ]
