# Generated by Django 5.0.3 on 2026-08-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_contact_experience_column(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'career_applicationcontact'
    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
    if 'experience_id' in columns:
        return
    quote_name = connection.ops.quote_name
    reference = (
        ''
        if connection.vendor == 'postgresql'
        else ' REFERENCES "career_experience" ("id")'
    )
    with connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE {quote_name(table_name)} '
            f'ADD COLUMN {quote_name("experience_id")} bigint NULL{reference}'
        )
        if connection.vendor == 'postgresql':
            cursor.execute(
                f'ALTER TABLE {quote_name(table_name)} '
                'ADD CONSTRAINT "career_contact_experience_fk" '
                'FOREIGN KEY ("experience_id") REFERENCES "career_experience" ("id")'
            )


def add_experience_work_email(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'career_experience'
    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
    if 'work_email' in columns:
        return
    quote_name = connection.ops.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE {quote_name(table_name)} '
            f'ADD COLUMN {quote_name("work_email")} varchar(254) DEFAULT \'\' NOT NULL'
        )


def make_contact_application_nullable(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                'ALTER TABLE "career_applicationcontact" '
                'ALTER COLUMN "application_id" DROP NOT NULL'
            )
        return

    ApplicationContact = apps.get_model('career', 'ApplicationContact')
    Application = apps.get_model('career', 'Application')
    old_field = ApplicationContact._meta.get_field('application')
    new_field = models.ForeignKey(
        Application,
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name='contacts',
    )
    new_field.set_attributes_from_name('application')
    schema_editor.alter_field(ApplicationContact, old_field, new_field, strict=True)


class Migration(migrations.Migration):
    # This engine rejects three things Django emits by default: ALTER COLUMN ...
    # DROP DEFAULT, an inline CONSTRAINT on ADD COLUMN, and SET CONSTRAINTS (issued
    # when a deferrable FK is recreated). Each is worked around with raw SQL below,
    # so the migration can stay atomic.

    dependencies = [
        ("career", "0019_applicationcontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Split in two: this engine rejects an inline ``CONSTRAINT ... REFERENCES`` on
        # ADD COLUMN, but accepts a separate ADD CONSTRAINT. See migration 0017 for
        # the related DROP DEFAULT limitation.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_contact_experience_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="applicationcontact",
                    name="experience",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="career.experience",
                    ),
                ),
            ],
        ),
        # Wrapped because this engine rejects the ``ALTER COLUMN ... DROP DEFAULT``
        # Django emits after adding a defaulted column. See migration 0017.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_experience_work_email, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="experience",
                    name="work_email",
                    field=models.EmailField(
                        blank=True,
                        help_text="Your work email address at this job",
                        max_length=254,
                    ),
                ),
            ],
        ),
        # Only nullability changes here. Django would drop and recreate the FK as
        # deferrable and then issue SET CONSTRAINTS, which this engine rejects; the
        # existing constraint stays valid either way.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(make_contact_application_nullable, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="applicationcontact",
                    name="application",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="career.application",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="applicationcontact",
            index=models.Index(
                fields=["user", "experience"], name="career_contact_exp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcontact",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("application__isnull", False),
                    ("experience__isnull", False),
                    _connector="OR",
                ),
                name="contact_has_application_or_experience",
            ),
        ),
    ]
