# Generated by Django 5.0.3 on 2026-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0020_applicationcontact_experience_experience_work_email_and_more"),
    ]

    operations = [
        # Wrapped because this engine rejects the ``ALTER COLUMN ... DROP DEFAULT``
        # Django emits after adding a defaulted column. See migration 0017.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "career_application" '
                        "ADD COLUMN \"job_description\" text DEFAULT '' NOT NULL;"
                    ),
                    reverse_sql='ALTER TABLE "career_application" DROP COLUMN "job_description";',
                ),
            ],
            state_operations=[
            migrations.AddField(
                model_name="application",
                name="job_description",
                field=models.TextField(
                    blank=True,
                    help_text="Full job posting text, kept because postings are taken down while you interview",
                ),
            ),
            ],
        ),
    ]
