# Generated by Django 5.0.3 on 2026-08-02 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0021_application_job_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="submitted_documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Exact document versions sent with this application; a later version does not replace them",
                related_name="submitted_for_applications",
                to="career.document",
            ),
        ),
        migrations.CreateModel(
            name="InterviewDebrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=50)),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("questions_asked", models.TextField(blank=True)),
                ("went_well", models.TextField(blank=True)),
                ("weak_areas", models.TextField(blank=True)),
                ("interviewer_notes", models.TextField(blank=True)),
                ("confidence", models.SmallIntegerField(blank=True, null=True)),
                ("next_steps", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debriefs",
                        to="career.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_debriefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["interview_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "application"], name="career_debrief_app_idx"
                    )
                ],
            },
        ),
    ]
