# Generated by Django 5.0.3 on 2026-08-03 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0023_career_relationship_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
    ]
