# Generated by Django 5.0.3 on 2026-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0024_remove_contact_linkedin_url_remove_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrelationship",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CONTACT", "Contact"),
                    ("RECRUITER", "Recruiter"),
                    ("INTERVIEWER", "Interviewer"),
                    ("HIRING_MANAGER", "Hiring Manager"),
                    ("MANAGER", "Manager"),
                    ("DIRECT_TEAMMATE", "Direct Teammate"),
                    ("COWORKER", "Coworker"),
                    ("TECH_LEAD", "Tech Lead"),
                    ("MENTOR", "Mentor"),
                    ("WORKS_WITH", "Works With"),
                    ("CUSTOM", "Custom"),
                ],
                default="CONTACT",
                max_length=30,
            ),
        ),
    ]
