# Generated by Django 5.0.3 on 2026-08-03 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0025_alter_contactrelationship_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactcontext",
            name="notes",
        ),
    ]
