# Generated by Django 5.0.3 on 2026-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0026_experience_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("internship", "Internship"),
                    ("contract", "Contract"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=20,
                null=True,
            ),
        ),
    ]
