# Generated by Django 5.0.3 on 2026-08-21 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0030_application_free_food_meals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="equity_cliff_months",
            field=models.PositiveSmallIntegerField(
                default=12, db_default=12, help_text="Months before the first equity vests"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="equity_vesting_years",
            field=models.PositiveSmallIntegerField(
                default=4, db_default=4, help_text="Years over which the initial grant vests"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="equity_vests_per_year",
            field=models.PositiveSmallIntegerField(
                default=4, db_default=4, help_text="Vest occasions per year, e.g. 2 for twice a year"
            ),
        ),
        migrations.CreateModel(
            name="IncomeYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_year", models.PositiveIntegerField()),
                (
                    "source_key",
                    models.CharField(
                        default="",
                        help_text="Which role these elections belong to, e.g. experience-10 or offer-3",
                        max_length=64,
                    ),
                ),
                (
                    "first_pay_date",
                    models.DateField(
                        blank=True,
                        help_text="Anchors pay periods to real dates so vests land in the right one",
                        null=True,
                    ),
                ),
                (
                    "salary_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "paychecks_per_year_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "pretax_401k_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "roth_401k_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "hsa_per_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fsa_per_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "post_tax_deductions_per_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medical_premium_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dental_premium_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vision_premium_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dependent_premium_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "custom_deductions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, label, amount, treatment}] where treatment is SECTION_125, PRETAX_INCOME_ONLY or POST_TAX",
                    ),
                ),
                (
                    "period_deductions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{periodIndex, medical, dental, vision, dependent, pretax401kPercent, roth401kPercent, customAmounts}] overrides for a single paycheck",
                    ),
                ),
                (
                    "exclude_allowances_from_deferral_base",
                    models.BooleanField(
                        default=False,
                        help_text="Compute 401(k) deferrals and the match on base pay, excluding allowances",
                    ),
                ),
                (
                    "match_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, matchPercent, uptoPercent}] employer 401(k) match bands, e.g. 100% to 3% then 50% to 5%",
                    ),
                ),
                (
                    "match_non_elective_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Employer contribution paid regardless of deferral, e.g. a safe-harbor 3%",
                        max_digits=6,
                    ),
                ),
                (
                    "match_annual_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Dollar ceiling on the employer's yearly contribution. 0 means none.",
                        max_digits=12,
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, label, amount, treatment, timesPer, unit}] allowances; unit is PAYCHECK, MONTH or YEAR",
                    ),
                ),
                (
                    "retirement_starting_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="401(k) balance at the start of the tax year",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "retirement_current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current 401(k) balance, used to derive investment gains",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("hsa_family_coverage", models.BooleanField(default=False)),
                (
                    "age_50_plus",
                    models.BooleanField(
                        default=False, help_text="Enables the 401(k) catch-up limit"
                    ),
                ),
                (
                    "include_bonus",
                    models.BooleanField(
                        default=False,
                        help_text="Off by default: a bonus only lands once its payout schedule is set",
                    ),
                ),
                (
                    "bonus_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual bonus. Null falls back to the offer's target bonus.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "bonus_payouts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, periodIndex, payDate, percent}] shares of the bonus. payDate means paid off-cycle.",
                    ),
                ),
                (
                    "bonus_multiplier_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Company performance multiplier applied to the target bonus",
                        max_digits=6,
                    ),
                ),
                (
                    "bonus_extras",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, label, amount}] discretionary bonuses stacked on top of the target",
                    ),
                ),
                (
                    "bonus_prorated",
                    models.BooleanField(
                        default=True,
                        help_text="Scale the target bonus by the share of the performance year the role covers",
                    ),
                ),
                (
                    "bonus_performance_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year the bonus was earned. Null means the year before it is paid.",
                        null=True,
                    ),
                ),
                (
                    "include_vest_events",
                    models.BooleanField(
                        default=False,
                        help_text="Off by default: vest events are only generated once the vesting terms are confirmed",
                    ),
                ),
                (
                    "total_grant_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "vests_per_year_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cliff_months_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "vesting_years_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "first_vest_date",
                    models.DateField(
                        blank=True,
                        help_text="Grant or first vest date. Defaults to the role start date.",
                        null=True,
                    ),
                ),
                (
                    "income_events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, kind, periodIndex, amount, label}] where kind is bonus, vest or other",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_years",
                        to="career.experience",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_years",
                        to="career.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tax_year"],
                "unique_together": {("user", "tax_year", "source_key")},
            },
        ),
        migrations.CreateModel(
            name="PaycheckActual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_index",
                    models.PositiveSmallIntegerField(help_text="1-based pay period"),
                ),
                ("pay_date", models.DateField(blank=True, null=True)),
                (
                    "actual_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_federal_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_state_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_social_security",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_medicare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "income_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actuals",
                        to="career.incomeyear",
                    ),
                ),
            ],
            options={
                "ordering": ["period_index"],
                "unique_together": {("income_year", "period_index")},
            },
        ),
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_year", models.PositiveIntegerField()),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED_FILING_JOINTLY", "Married Filing Jointly"),
                            ("MARRIED_FILING_SEPARATELY", "Married Filing Separately"),
                            ("HEAD_OF_HOUSEHOLD", "Head of Household"),
                        ],
                        default="SINGLE",
                        max_length=30,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Two-letter residence state. Blank derives it from the offer location.",
                        max_length=2,
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Local wage tax jurisdiction, e.g. NYC",
                        max_length=50,
                    ),
                ),
                (
                    "w4_dependents_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="W-4 Step 3 annual credit amount",
                        max_digits=10,
                    ),
                ),
                (
                    "w4_other_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="W-4 Step 4a",
                        max_digits=12,
                    ),
                ),
                (
                    "w4_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="W-4 Step 4b",
                        max_digits=12,
                    ),
                ),
                (
                    "w4_extra_withholding_per_period",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="W-4 Step 4c",
                        max_digits=10,
                    ),
                ),
                (
                    "state_flat_rate_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Effective state rate percent, used when the state is not modelled",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tax_year"],
                "unique_together": {("user", "tax_year")},
            },
        ),
    ]
