# Generated by Django 5.0.3 on 2026-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "career",
            "0031_offer_equity_cliff_months_offer_equity_vesting_years_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomeyear",
            name="allowances",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{id, label, amount, treatment, timesPer, unit, payOn, payPeriodIndex}] allowances; unit is PAYCHECK, MONTH, YEAR or ONCE; payPeriodIndex names the paycheck a ONCE allowance lands on",
            ),
        ),
    ]
