# Generated by Django 5.0.3 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0032_alter_incomeyear_allowances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycheckactual",
            name="actual_federal_tax",
        ),
        migrations.RemoveField(
            model_name="paycheckactual",
            name="actual_medicare",
        ),
        migrations.RemoveField(
            model_name="paycheckactual",
            name="actual_social_security",
        ),
        migrations.RemoveField(
            model_name="paycheckactual",
            name="actual_state_tax",
        ),
    ]
