# Generated by Django 5.0.3 on 2026-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0036_multi_user_ownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="employment_type",
            field=models.CharField(
                blank=True, default="full_time", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(
                blank=True, default="full_time", max_length=20, null=True
            ),
        ),
    ]
