# Generated by Django 5.0.3 on 2026-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0037_alter_application_employment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="logo",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
