# Generated by Django 5.0.3 on 2026-05-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0047_googleoauthcredential_googleoauthstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("JD_REPORT", "JD Report"),
                            ("COVER_LETTER", "Cover Letter"),
                            ("NEGOTIATION_RESULT", "Negotiation Result"),
                        ],
                        max_length=40,
                    ),
                ),
                ("client_id", models.CharField(max_length=120)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_locked", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_artifacts",
                        to="career.application",
                    ),
                ),
                (
                    "source_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_artifacts",
                        to="career.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="aiartifact",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"),
                name="unique_ai_artifact_client_id_per_user",
            ),
        ),
    ]
