# Generated by Django 5.0.3 on 2026-05-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0049_offerdecisionsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetsyncconfig",
            name="overwrite_strategies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="GoogleSheetSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("error_details", models.TextField(blank=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="career.googlesheetsyncconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
