# Every migration for this app, collapsed into one, generated from the current models.
# Generated by Django 5.0.3 on 2026-09-07 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True


    dependencies = [
        ("career", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("availability_text", models.CharField(max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailabilitySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_key_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "group_id",
                    models.CharField(
                        blank=True,
                        help_text="Group UUID for multi-day holidays",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("holiday_type", models.CharField(default="custom", max_length=20)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Locked holidays cannot be deleted"
                    ),
                ),
                (
                    "tab",
                    models.CharField(
                        blank=True,
                        help_text="Custom tab id this holiday belongs to",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_holidays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.CharField(max_length=20)),
                ("end_time", models.CharField(max_length=20)),
                (
                    "timezone",
                    models.CharField(default="America/Los_Angeles", max_length=64),
                ),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="virtual",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=500)),
                ("meeting_link", models.URLField(blank=True, max_length=500)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_rule", models.JSONField(blank=True, null=True)),
                ("override_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("reminder_minutes", models.IntegerField(default=15)),
                ("is_all_day", models.BooleanField(default=False)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Locked events cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="career.application",
                    ),
                ),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="availability.event",
                    ),
                ),
                (
                    "span_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_overrides",
                        to="availability.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ConflictAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "event1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_event1",
                        to="availability.event",
                    ),
                ),
                (
                    "event2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_event2",
                        to="availability.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event Categories",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="availability.eventcategory",
            ),
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("host_display_name", models.CharField(blank=True, max_length=120)),
                (
                    "host_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("public_note", models.TextField(blank=True)),
                ("duration_days", models.IntegerField(default=7)),
                ("booking_block_minutes", models.IntegerField(default=30)),
                ("buffer_minutes", models.IntegerField(default=0)),
                ("max_bookings_per_day", models.IntegerField(default=0)),
                (
                    "allow_reschedule_cancel",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to reschedule or cancel bookings",
                    ),
                ),
                (
                    "reschedule_cancel_deadline_hours",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum hours before a booking when public reschedule/cancel remains available. 0 disables the cutoff.",
                    ),
                ),
                (
                    "intake_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom questions for booking intake [{id, label, type, required}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Locked links cannot be deleted"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("start_time", models.CharField(max_length=20)),
                ("end_time", models.CharField(max_length=20)),
                (
                    "timezone",
                    models.CharField(default="America/Los_Angeles", max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                ("intake_answers", models.JSONField(blank=True, default=dict)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("canceled", "Canceled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Locked bookings cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_booking",
                        to="availability.event",
                    ),
                ),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="availability.sharelink",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_time", models.TimeField(default="09:00:00")),
                ("work_end_time", models.TimeField(default="17:00:00")),
                (
                    "work_time_ranges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of time ranges [{start: 'HH:MM:SS', end: 'HH:MM:SS'}]. Overrides work_start_time/work_end_time when non-empty.",
                    ),
                ),
                ("work_days", models.JSONField(default=list)),
                ("default_event_duration", models.IntegerField(default=60)),
                ("buffer_time", models.IntegerField(default=0)),
                (
                    "availability_weeks",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of weeks to generate on the Availability page",
                    ),
                ),
                (
                    "primary_timezone",
                    models.CharField(default="America/Los_Angeles", max_length=50),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("notification_preferences", models.JSONField(default=dict)),
                ("global_availability", models.JSONField(default=dict)),
                (
                    "ghosting_threshold_days",
                    models.IntegerField(
                        default=30,
                        help_text="Days of inactivity before marking application as ghosted",
                    ),
                ),
                (
                    "default_mpg",
                    models.DecimalField(
                        decimal_places=1,
                        default=28,
                        help_text="Fuel efficiency used for commute cost",
                        max_digits=6,
                    ),
                ),
                (
                    "default_gas_price_per_gallon",
                    models.DecimalField(
                        decimal_places=2,
                        default=4,
                        help_text="Pump price used for commute cost",
                        max_digits=6,
                    ),
                ),
                (
                    "ignored_federal_holidays",
                    models.JSONField(
                        default=list,
                        help_text="List of federal holiday names or dates to ignore",
                    ),
                ),
                (
                    "employment_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom employment type definitions [{value, label, color}]",
                    ),
                ),
                (
                    "holiday_tabs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User-defined holiday tab definitions [{id, name}]",
                    ),
                ),
                (
                    "default_holiday_color",
                    models.CharField(
                        default="green",
                        help_text="Colour for time off that has no holiday tab (the My Time Off bucket)",
                        max_length=32,
                    ),
                ),
                (
                    "federal_holiday_color",
                    models.CharField(
                        default="gray",
                        help_text="Colour for observed federal holidays",
                        max_length=32,
                    ),
                ),
                (
                    "offer_adjustment_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Offer comparison scenarios and adjustment assumptions: {maritalStatus, simulatedOffers, savedAt}",
                    ),
                ),
                (
                    "application_stages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom application timeline stages [{key, label, shortLabel, tone}]",
                    ),
                ),
                (
                    "hidden_nav_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of nav route keys to hide from sidebar",
                    ),
                ),
                (
                    "hidden_income_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Income source keys to leave out of the Income page role picker",
                    ),
                ),
                (
                    "hidden_income_years",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tax years to leave out of the Income page year picker",
                    ),
                ),
                (
                    "mobile_toolbar_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of route keys pinned to the mobile toolbar",
                    ),
                ),
                (
                    "nav_item_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of sidebar route keys; keys absent from the list keep their built-in order",
                    ),
                ),
                (
                    "nav_item_labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom sidebar names keyed by route, e.g. {'/tasks': 'To Do'}; absent keys keep their built-in name",
                    ),
                ),
                (
                    "custom_analytics_widgets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User-authored analytics widgets [{id, name, query, widgetType, icon, color, createdAt, queryType, visualConfig}]",
                    ),
                ),
                (
                    "analytics_widget_order",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Widget order per dashboard, e.g. {'jobHunt': [...], 'availability': [...]}",
                    ),
                ),
                (
                    "analytics_widgets_enabled",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which widgets are shown per dashboard, e.g. {'jobHunt': {'funnel': true}}",
                    ),
                ),
                (
                    "contact_network_positions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hand-dragged contact graph layout: {'nodes': {id: {x, y}}, 'labels': {id: {x, y}}}",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked settings cannot be edited until unlocked",
                    ),
                ),
                (
                    "ai_provider_adapter",
                    models.CharField(
                        choices=[
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                            ("openai", "OpenAI"),
                            ("openrouter", "OpenRouter"),
                            ("custom", "Custom"),
                        ],
                        default="gemini",
                        help_text="Provider protocol used by the authenticated user's BYOK configuration.",
                        max_length=32,
                    ),
                ),
                (
                    "ai_provider_endpoint",
                    models.URLField(
                        blank=True,
                        default="https://generativelanguage.googleapis.com/v1beta",
                        help_text="Stored AI provider endpoint for the authenticated user's BYOK configuration.",
                        max_length=500,
                    ),
                ),
                (
                    "ai_provider_model",
                    models.CharField(
                        blank=True,
                        default="gemini-3-flash-preview",
                        help_text="Stored AI provider model name for the authenticated user's BYOK configuration.",
                        max_length=255,
                    ),
                ),
                (
                    "ai_provider_api_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted AI provider API key for the authenticated user.",
                    ),
                ),
                (
                    "account_deletion_requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the authenticated user requested account deletion.",
                        null=True,
                    ),
                ),
                (
                    "account_deletion_scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the account becomes eligible for permanent deletion.",
                        null=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Public display name for booking links",
                        max_length=120,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Public profile picture for booking links",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_event_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="availability.eventcategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_settings_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AddConstraint(
            model_name="availabilityoverride",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_availability_override_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilitysetting",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_availability_setting_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcategory",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_event_category_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicbooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("share_link", "date", "start_time", "end_time"),
                name="unique_active_public_booking_slot",
            ),
        ),
    ]
