# Generated by Django 5.0.3 on 2026-06-15 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked holidays cannot be deleted')),
                ('group_id', models.CharField(blank=True, help_text='Group UUID for multi-day holidays', max_length=50, null=True)),
                ('holiday_type', models.CharField(default='custom', max_length=20)),
                ('tab', models.CharField(blank=True, help_text='Custom tab id this holiday belongs to', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_holidays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability_text', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_key_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('booking_block_minutes', models.IntegerField(default=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('timezone', models.CharField(choices=[('PT', 'Pacific Time'), ('ET', 'Eastern Time'), ('CT', 'Central Time'), ('MT', 'Mountain Time')], default='PT', max_length=2)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('location_type', models.CharField(choices=[('in_person', 'In-Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='availability.event')),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('reminder_minutes', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='availability.eventcategory')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='career.application')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked events cannot be deleted')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConflictAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('event1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_event1', to='availability.event')),
                ('event2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_event2', to='availability.event')),
            ],
        ),
        migrations.CreateModel(
            name='PublicBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('timezone', models.CharField(default='PT', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='availability.sharelink')),
            ],
            options={
                'ordering': ['date', 'start_time'],

            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default='09:00:00')),
                ('work_end_time', models.TimeField(default='17:00:00')),
                ('work_days', models.JSONField(default=list)),
                ('default_event_duration', models.IntegerField(default=60)),
                ('buffer_time', models.IntegerField(default=0)),
                ('primary_timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('global_availability', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ghosting_threshold_days', models.IntegerField(default=30, help_text='Days of inactivity before marking application as ghosted')),
                ('default_event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='availability.eventcategory')),
                ('ignored_federal_holidays', models.JSONField(default=list, help_text='List of federal holiday names or dates to ignore')),
                ('employment_types', models.JSONField(blank=True, default=list, help_text='Custom employment type definitions [{value, label, color}]')),
                ('holiday_tabs', models.JSONField(blank=True, default=list, help_text='User-defined holiday tab definitions [{id, name}]')),
                ('hidden_nav_items', models.JSONField(blank=True, default=list, help_text='List of nav route keys to hide from sidebar')),
                ('work_time_ranges', models.JSONField(blank=True, default=list, help_text="List of time ranges [{start: 'HH:MM:SS', end: 'HH:MM:SS'}]. Overrides work_start_time/work_end_time when non-empty.")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_availability_override_per_user'),
        ),
        migrations.AddConstraint(
            model_name='availabilitysetting',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_availability_setting_per_user'),
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_event_category_per_user'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_provider_api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted AI provider API key for the authenticated user.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='application_stages',
            field=models.JSONField(blank=True, default=list, help_text='Custom application timeline stages [{key, label, shortLabel, tone}]'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_provider_adapter',
            field=models.CharField(choices=[('claude', 'Claude'), ('gemini', 'Gemini'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], default='gemini', help_text="Provider protocol used by the authenticated user's BYOK configuration.", max_length=32),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_provider_endpoint',
            field=models.URLField(blank=True, default='https://generativelanguage.googleapis.com/v1beta', help_text="Stored AI provider endpoint for the authenticated user's BYOK configuration.", max_length=500),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_provider_model',
            field=models.CharField(blank=True, default='gemini-3-flash-preview', help_text="Stored AI provider model name for the authenticated user's BYOK configuration.", max_length=255),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='buffer_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='host_display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='max_bookings_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='public_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked bookings cannot be deleted'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked links cannot be deleted'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='host_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public display name for booking links', max_length=120),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Public profile picture for booking links', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='account_deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the authenticated user requested account deletion.', null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='account_deletion_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When the account becomes eligible for permanent deletion.', null=True),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='intake_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='allow_reschedule_cancel',
            field=models.BooleanField(default=True, help_text='Allow users to reschedule or cancel bookings'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='intake_questions',
            field=models.JSONField(blank=True, default=list, help_text='Custom questions for booking intake [{id, label, type, required}]'),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_booking', to='availability.event'),
        ),
        migrations.AddConstraint(
            model_name='publicbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('share_link', 'date', 'start_time', 'end_time'), name='unique_active_public_booking_slot'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='availability_weeks',
            field=models.PositiveIntegerField(default=2, help_text='Number of weeks to generate on the Availability page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=64),
        ),
        migrations.AlterField(
            model_name='publicbooking',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=64),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='reschedule_cancel_deadline_hours',
            field=models.IntegerField(default=0, help_text='Minimum hours before a booking when public reschedule/cancel remains available. 0 disables the cutoff.'),
        ),
        migrations.AddField(
            model_name='publicbooking',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ai_provider_adapter',
            field=models.CharField(choices=[('claude', 'Claude'), ('gemini', 'Gemini'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('custom', 'Custom')], default='gemini', help_text="Provider protocol used by the authenticated user's BYOK configuration.", max_length=32),
        ),
    ]
