# Generated by Django 5.2.10 on 2026-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0002_customholiday_is_recurring"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("availability_text", models.CharField(max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
