# Generated by Django 5.0.3 on 2026-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0003_usersettings_mobile_toolbar_items"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "availability_usersettings" '
                        "ADD COLUMN \"offer_adjustment_settings\" jsonb DEFAULT '{}'::jsonb NOT NULL;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "availability_usersettings" '
                        'DROP COLUMN "offer_adjustment_settings";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="usersettings",
                    name="offer_adjustment_settings",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Offer comparison scenarios and adjustment assumptions: "
                            "{maritalStatus, simulatedOffers, savedAt}"
                        ),
                    ),
                ),
            ],
        ),
    ]
