# Generated by Django 5.0.3 on 2026-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0005_event_is_all_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
