# Generated by Django 5.2.10 on 2026-02-01 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0009_event_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
