# Generated by Django 5.0.3 on 2026-03-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0014_sharelink_booking_block_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customholiday",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customholiday",
            name="date",
            field=models.DateField(),
        ),
    ]
