# Generated by Django 5.0.3 on 2026-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0016_remove_customholiday_end_date_customholiday_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ignored_federal_holidays",
            field=models.JSONField(
                default=list,
                help_text="List of federal holiday names or dates to ignore",
            ),
        ),
    ]
