# Generated by Django 5.0.3 on 2026-04-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0025_usersettings_ai_provider_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="application_stages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom application timeline stages [{key, label, shortLabel, tone}]",
            ),
        ),
    ]
