# Generated by Django 5.0.3 on 2026-05-03 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0033_usersettings_account_deletion_grace"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicbooking",
            name="intake_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="publicbooking",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("canceled", "Canceled")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="publicbooking",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="allow_reschedule_cancel",
            field=models.BooleanField(
                default=True, help_text="Allow users to reschedule or cancel bookings"
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="intake_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom questions for booking intake [{id, label, type, required}]",
            ),
        ),
    ]
