# Generated by Django 5.0.3 on 2026-05-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0035_publicbooking_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="availability_weeks",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Number of weeks to generate on the Availability page",
            ),
        ),
    ]
