# Generated by Django 5.0.3 on 2026-05-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0036_usersettings_availability_weeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="availability_weeks",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Number of weeks to generate on the Availability page",
            ),
        ),
    ]
