import os
import sys
from datetime import timedelta
from urllib.parse import parse_qsl, unquote, urlparse

"""
Django settings for availability_project project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parents[2]

SUPPORTED_ENVIRONMENTS = {"development", "production", "test"}


def get_environment_name():
    value = os.environ.get("DJANGO_ENV")
    if value is not None:
        normalized = value.strip().lower()
        return normalized or "development"

    return "development" if (BASE_DIR / ".env.development").exists() else "production"


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    raw_value = os.environ.get(name, default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def is_test_process():
    command_names = {Path(arg).name for arg in sys.argv if arg}
    return (
        "PYTEST_CURRENT_TEST" in os.environ
        or "pytest" in command_names
        or "test" in sys.argv[1:]
    )


def secret_key_is_weak(value):
    if not value:
        return True

    secret = value.strip()
    if secret.startswith("django-insecure") or secret.startswith("replace-me"):
        return True

    if len(secret) < 50:
        return True

    return len(set(secret)) < 5


def default_sqlite_database():
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


def database_config_from_url():
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        if ENVIRONMENT == "production":
            raise ImproperlyConfigured(
                "DATABASE_URL must be set when DJANGO_ENV=production."
            )
        return default_sqlite_database()

    parsed = urlparse(database_url)
    scheme = parsed.scheme.split("+", 1)[0].lower()
    if scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured(
            "DATABASE_URL must use a PostgreSQL scheme such as postgres:// or postgresql://."
        )

    database_name = unquote(parsed.path.lstrip("/"))
    if not database_name:
        raise ImproperlyConfigured("DATABASE_URL must include a database name.")

    query_options = {
        key: value for key, value in parse_qsl(parsed.query, keep_blank_values=True)
    }

    database_config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": database_name,
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or 5432),
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": env_bool("DB_CONN_HEALTH_CHECKS", True),
    }

    if query_options:
        database_config["OPTIONS"] = query_options

    return database_config


ENVIRONMENT = get_environment_name()
if ENVIRONMENT not in SUPPORTED_ENVIRONMENTS:
    supported = ", ".join(sorted(SUPPORTED_ENVIRONMENTS))
    raise ImproperlyConfigured(
        f"DJANGO_ENV must be one of: {supported}. Got {ENVIRONMENT!r}."
    )

load_dotenv(BASE_DIR / f".env.{ENVIRONMENT}")
IS_PRODUCTION = ENVIRONMENT == "production"
IS_TEST = ENVIRONMENT == "test" or is_test_process()
IS_DEVELOPMENT = not IS_PRODUCTION


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DEBUG", IS_DEVELOPMENT)

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if IS_DEVELOPMENT:
        SECRET_KEY = "django-insecure-local-dev-only"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False.")

if IS_PRODUCTION and secret_key_is_weak(SECRET_KEY):
    raise ImproperlyConfigured(
        "SECRET_KEY must be a strong random value when DEBUG=False."
    )

DEFAULT_ALLOWED_HOSTS = "localhost,127.0.0.1" if IS_DEVELOPMENT else ""
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)
for vercel_host_env in ("VERCEL_URL", "VERCEL_BRANCH_URL", "VERCEL_PROJECT_PRODUCTION_URL"):
    vercel_host = (os.environ.get(vercel_host_env) or "").strip()
    if vercel_host and vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_host)
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must include your deployed hostnames.")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "availability",
    "career",
    "analytics",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

DEFAULT_FRONTEND_ORIGINS = (
    "http://localhost:5173,http://127.0.0.1:5173" if IS_DEVELOPMENT else ""
)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", DEFAULT_FRONTEND_ORIGINS)
CORS_ALLOWED_ORIGIN_REGEXES = env_list("CORS_ALLOWED_ORIGIN_REGEXES", "")
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", False)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", DEFAULT_FRONTEND_ORIGINS)
PUBLIC_FRONTEND_BASE_URL = os.environ.get("PUBLIC_FRONTEND_BASE_URL", "").rstrip("/")

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "api.wsgi.app"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": database_config_from_url()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "login": os.environ.get("DRF_LOGIN_RATE", "5/minute"),
        "signup": os.environ.get("DRF_SIGNUP_RATE", "3/hour"),
        "token_refresh": os.environ.get("DRF_TOKEN_REFRESH_RATE", "30/hour"),
        "ai_provider_relay": os.environ.get("DRF_AI_PROVIDER_RELAY_RATE", "20/hour"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_TOKEN_DAYS", "14"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SIGNING_KEY", SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

ALLOW_PUBLIC_SIGNUP = env_bool("ALLOW_PUBLIC_SIGNUP", False)
AUTO_LOGIN_AFTER_SIGNUP = env_bool("AUTO_LOGIN_AFTER_SIGNUP", False)

# Media configuration for file uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
BLOB_READ_WRITE_TOKEN = (os.environ.get("BLOB_READ_WRITE_TOKEN") or "").strip()
DOCUMENT_BLOB_READ_WRITE_TOKEN = (os.environ.get("DOCUMENT_BLOB_READ_WRITE_TOKEN") or "").strip()
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(2_621_440))
)
_configured_document_upload_bytes = int(
    os.environ.get("MAX_DOCUMENT_UPLOAD_BYTES", str(10 * 1024 * 1024))
)
MAX_DOCUMENT_UPLOAD_BYTES = (
    min(_configured_document_upload_bytes, 4 * 1024 * 1024)
    if DOCUMENT_BLOB_READ_WRITE_TOKEN
    else _configured_document_upload_bytes
)
_configured_logo_upload_bytes = int(
    os.environ.get("MAX_LOGO_UPLOAD_BYTES", str(5 * 1024 * 1024))
)
MAX_LOGO_UPLOAD_BYTES = min(_configured_logo_upload_bytes, 4 * 1024 * 1024) if BLOB_READ_WRITE_TOKEN else _configured_logo_upload_bytes
MAX_IMPORT_FILE_BYTES = int(
    os.environ.get("MAX_IMPORT_FILE_BYTES", str(5 * 1024 * 1024))
)
MAX_IMPORT_ROWS = max(1, int(os.environ.get("MAX_IMPORT_ROWS", "1000")))

ENABLE_ADMIN = env_bool("ENABLE_ADMIN", False)
ADMIN_URL = os.environ.get("ADMIN_URL", "admin/")

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", IS_PRODUCTION)
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_DOMAIN = os.environ.get("SESSION_COOKIE_DOMAIN") or None
CSRF_COOKIE_DOMAIN = os.environ.get("CSRF_COOKIE_DOMAIN") or None
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = int(
    os.environ.get("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "same-origin")
X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")
AI_PROVIDER_ENCRYPTION_KEY = os.environ.get("AI_PROVIDER_ENCRYPTION_KEY", SECRET_KEY)
AI_PROVIDER_ALLOWED_HOSTS = env_list("AI_PROVIDER_ALLOWED_HOSTS", "")
AI_PROVIDER_REQUIRE_HTTPS = env_bool("AI_PROVIDER_REQUIRE_HTTPS", IS_PRODUCTION)
AI_PROVIDER_RESTRICT_PRIVATE_NETWORKS = env_bool(
    "AI_PROVIDER_RESTRICT_PRIVATE_NETWORKS", IS_PRODUCTION
)
AI_PROVIDER_REQUEST_TIMEOUT_SECONDS = int(
    os.environ.get("AI_PROVIDER_REQUEST_TIMEOUT_SECONDS", "30")
)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_SUCCESS_REDIRECT_URL = os.environ.get("GOOGLE_OAUTH_SUCCESS_REDIRECT_URL", "")

# Cache TTL used across the project (in seconds)
CACHE_TTL = 300  # 5 minutes
REDIS_URL = (os.environ.get("REDIS_URL") or "").strip()

if IS_TEST or not REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": f"careerhub-{ENVIRONMENT}-cache",
            "TIMEOUT": CACHE_TTL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "TIMEOUT": CACHE_TTL,
            "TEST": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            },
        }
    }
