# Generated by Django 5.2.10 on 2026-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("start_time_obj", models.TimeField(null=True)),
                ("end_time_obj", models.TimeField(null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("PT", "Pacific Time"),
                            ("ET", "Eastern Time"),
                            ("CT", "Central Time"),
                            ("MT", "Mountain Time"),
                        ],
                        default="PT",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
    ]
