# Generated by Django 5.2.10 on 2026-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0003_availabilityoverride"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
    ]
