# Generated by Django 5.2.10 on 2026-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0004_availabilitysetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_time_obj",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time_obj",
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.CharField(max_length=20),
        ),
    ]
