# Generated by Django 5.2.10 on 2026-01-31 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0005_remove_event_end_time_obj_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("interview", "Interview"),
                            ("meeting", "Meeting"),
                            ("personal", "Personal"),
                            ("study", "Study"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("color", models.CharField(max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Event Categories",
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("duration_days", models.IntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_time", models.TimeField(default="09:00:00")),
                ("work_end_time", models.TimeField(default="17:00:00")),
                ("work_days", models.JSONField(default=list)),
                ("default_event_duration", models.IntegerField(default=60)),
                ("buffer_time", models.IntegerField(default=0)),
                (
                    "primary_timezone",
                    models.CharField(default="America/Los_Angeles", max_length=50),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("notification_preferences", models.JSONField(default=dict)),
                ("global_availability", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In-Person"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                default="virtual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="availability.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_rule",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_minutes",
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ConflictAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "event1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_event1",
                        to="availability.event",
                    ),
                ),
                (
                    "event2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_event2",
                        to="availability.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="availability.eventcategory",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="availability.tag"
            ),
        ),
    ]
