# Generated by Django 5.2.10 on 2026-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "availability",
            "0006_eventcategory_sharelink_tag_usersettings_event_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
