# Generated by Django 5.0.3 on 2026-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0007_alter_eventcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ghosting_threshold_days",
            field=models.IntegerField(
                default=30,
                help_text="Days of inactivity before marking application as ghosted",
            ),
        ),
    ]
