# Generated by Django 5.0.3 on 2026-02-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0008_usersettings_ghosting_threshold_days"),
        ("career", "0003_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="career.application",
            ),
        ),
    ]
