# Generated by Django 5.0.3 on 2026-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0010_remove_event_tags_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="customholiday",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked holidays cannot be deleted"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked events cannot be deleted"
            ),
        ),
    ]
