# Generated by Django 5.0.3 on 2026-02-16 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0011_customholiday_is_locked_event_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="default_event_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="availability.eventcategory",
            ),
        ),
    ]
