# Generated by Django 5.0.3 on 2026-03-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0015_customholiday_end_date_alter_customholiday_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customholiday",
            name="end_date",
        ),
        migrations.AddField(
            model_name="customholiday",
            name="group_id",
            field=models.CharField(
                blank=True,
                help_text="Group UUID for multi-day holidays",
                max_length=50,
                null=True,
            ),
        ),
    ]
