# Generated by Django 5.0.3 on 2026-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0017_usersettings_ignored_federal_holidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="customholiday",
            name="holiday_type",
            field=models.CharField(default="custom", max_length=20),
        ),
    ]
