# Generated by Django 5.0.3 on 2026-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0028_sharelink_booking_polish"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicbooking",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked bookings cannot be deleted"
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked links cannot be deleted"
            ),
        ),
    ]
