# Generated by Django 5.0.3 on 2026-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0029_publicbooking_is_locked_sharelink_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="host_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
