# Generated by Django 5.0.3 on 2026-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0030_sharelink_host_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="host_avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
