# Generated by Django 5.0.3 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0031_sharelink_host_avatar_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharelink",
            name="host_avatar_url",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="profile_picture_url",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Public display name for booking links",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Public profile picture for booking links",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
