# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0032_remove_sharelink_host_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="account_deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the authenticated user requested account deletion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="account_deletion_scheduled_for",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account becomes eligible for permanent deletion.",
                null=True,
            ),
        ),
    ]
