# Generated by Codex on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0034_publicbooking_intake_answers_publicbooking_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publicbooking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="publicbooking",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_booking",
                to="availability.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicbooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("share_link", "date", "start_time", "end_time"),
                name="unique_active_public_booking_slot",
            ),
        ),
    ]
