# Generated by Django 5.0.3 on 2026-01-31 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_title", models.CharField(max_length=255)),
                ("job_link", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WISHLIST", "Wishlist"),
                            ("APPLIED", "Applied"),
                            ("OA", "Online Assessment"),
                            ("SCREEN", "Phone Screen"),
                            ("ONSITE", "Onsite Interview"),
                            ("OFFER", "Offer Received"),
                            ("REJECTED", "Rejected"),
                            ("ACCEPTED", "Accepted"),
                            ("GHOSTED", "Ghosted"),
                        ],
                        default="WISHLIST",
                        max_length=20,
                    ),
                ),
                (
                    "rto_policy",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("ONSITE", "Onsite"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, help_text="e.g. $150k - $180k", max_length=100
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("date_applied", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="career.company",
                    ),
                ),
            ],
        ),
    ]
