# Generated by Django 5.0.3 on 2026-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="current_round",
            field=models.IntegerField(
                default=0, help_text="Current interview round number (0 for none)"
            ),
        ),
    ]
