# Generated by Django 5.2.10 on 2026-02-01 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0003_alter_application_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Annual Base Salary", max_digits=12
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual Target Bonus",
                        max_digits=12,
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annualized Equity Value",
                        max_digits=12,
                    ),
                ),
                (
                    "sign_on",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-time Sign On Bonus",
                        max_digits=12,
                    ),
                ),
                (
                    "benefits_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated Annual Benefits Value",
                        max_digits=12,
                    ),
                ),
                ("pto_days", models.IntegerField(default=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="career.application",
                    ),
                ),
            ],
        ),
    ]
