# Generated by Django 5.2.10 on 2026-02-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0004_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Is this your current role?"
            ),
        ),
    ]
