# Generated by Django 5.0.3 on 2026-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0005_offer_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked applications cannot be deleted"
            ),
        ),
    ]
