# Generated by Django 5.0.3 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0007_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked documents cannot be deleted"
            ),
        ),
    ]
