# Generated by Django 5.0.3 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0009_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="root_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="career.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
