# Generated by Django 5.0.3 on 2026-02-22

from django.db import migrations


def backfill_current_documents(apps, schema_editor):
    Document = apps.get_model("career", "Document")

    groups = {}
    for doc in Document.objects.all():
        root_id = doc.root_document_id or doc.id
        groups.setdefault(root_id, []).append(doc)

    for root_id, docs in groups.items():
        docs_sorted = sorted(
            docs,
            key=lambda d: (d.version_number or 1, d.updated_at, d.id),
            reverse=True,
        )
        current_doc = docs_sorted[0]
        Document.objects.filter(id=current_doc.id).update(is_current=True)
        stale_ids = [d.id for d in docs_sorted[1:]]
        if stale_ids:
            Document.objects.filter(id__in=stale_ids).update(is_current=False)


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0010_document_versioning"),
    ]

    operations = [
        migrations.RunPython(backfill_current_documents, migrations.RunPython.noop),
    ]
