# Generated by Django 5.0.3 on 2026-03-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0018_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
