# Generated by Django 5.0.3 on 2026-04-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0042_blank_optional_decision_signals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(default="APPLIED", max_length=50),
        ),
        migrations.AlterField(
            model_name="applicationtimelineentry",
            name="stage",
            field=models.CharField(max_length=50),
        ),
    ]
