# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0043_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='equity_vesting_schedule',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Four-year equity vesting percentages, e.g. [20, 20, 30, 30]',
            ),
        ),
    ]
