# Generated by Django 5.0.3 on 2026-05-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0044_offer_equity_vesting_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheetSyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sheet_url", models.URLField(max_length=2048)),
                ("spreadsheet_id", models.CharField(blank=True, max_length=255)),
                ("worksheet_name", models.CharField(blank=True, max_length=255)),
                ("gid", models.CharField(blank=True, max_length=64)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("APPLICATIONS", "Applications"),
                            ("EVENTS", "Events"),
                        ],
                        max_length=20,
                    ),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("header_row", models.PositiveSmallIntegerField(default=1)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("last_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sheet_sync_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleSheetSyncRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_key", models.CharField(max_length=255)),
                ("row_number", models.PositiveIntegerField()),
                ("row_hash", models.CharField(max_length=64)),
                ("local_object_type", models.CharField(max_length=50)),
                ("local_object_id", models.PositiveIntegerField()),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_rows",
                        to="career.googlesheetsyncconfig",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="googlesheetsyncconfig",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_google_sheet_sync_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="googlesheetsyncrow",
            constraint=models.UniqueConstraint(
                fields=("config", "external_key"),
                name="unique_google_sheet_row_per_config",
            ),
        ),
    ]
