# Generated by Django 5.0.3 on 2026-05-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0045_googlesheetsyncconfig_googlesheetsyncrow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetsyncconfig",
            name="sync_time",
            field=models.TimeField(
                default=datetime.time(22, 0),
                help_text="Preferred daily sync time in sync_timezone.",
            ),
        ),
        migrations.AddField(
            model_name="googlesheetsyncconfig",
            name="sync_timezone",
            field=models.CharField(default="America/Los_Angeles", max_length=64),
        ),
    ]
